server:
  port: 8071
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
chatgpt:
  api-key: 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
  #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 --> 3.5 turbo
  #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
  #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
  #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
  #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
  #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   # https://beta.openai.com/docs/quickstart/adjust-your-settings
  max-tokens: 1000
wa:
  appid:4WXX6T-XY5UXV8RTQ
dbsUrl:
  https://etech7-wf-etech7-db-service.azuremicroservices.io/
#spring:
#  cloud:
#    azure:
#      active-directory:
#        enabled: true
#        profile:
#          tenant-id: 8398dce0-ce72-4b68-857e-9ba585008d3e
#        credential:
#          client-id: dff403fb-0fe5-413b-888a-be22b5de238c
#          client-secret: 3c4ee371-ac7a-426b-bc2d-76d166eda39e
#        authorization-clients:
#          graph:
#            scopes: https://graph.microsoft.com/Analytics.Read, email
logging:
  level:
    root: info
#    org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
azure:
  application-insights:
    instrumentation-key: 0fbdefac-4b5b-4a1d-aeb9-af7711ff32f3
    enabled: true
    web:
      enabled: true
    logger:
      level:
        root: info
slack:
  webhook: https://hooks.slack.com/services/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
  #https://hooks.slack.com/services/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
#  https://hooks.slack.com/services/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